# This is a basic workflow to help you get started with Actions

name: Snyk

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Snyk
      uses: snyk/actions@0.1.1
      with:
        # Which Snyk command to run, defaults to test
        command: test # optional, default is test
        # Additional arguments to pass to Snyk
        #args: # optional
